sudo: false
dist: trusty
git:
  depth: 20000 # We're cloning a max of xxx commits, so the author date is correct
language: node_js
env:
  global:
    - GET_ENV_VAR=./_scripts/get_env.sh
    - GOPATH="${HOME}/.go_workspace"
    - HUGO_ENV=$($GET_ENV_VAR)
    - CF_APP=docs
    - CF_API=https://api.run.pivotal.io
    - CF_USERNAME=robert.rumyantsev@mendix.com
    - CF_ORGANIZATION=mxrobert-org
    - CF_SPACE=docs
    - CF_CLI_VERSION=6.22.2
    - HUGO_VERSION=0.31.1
    - secure: "VMTquDWxfptcxcxCURD1wBo8JtOY5qiv+dLYl6/HEwwkDMuNzWfVLmR8mbqBdXW+4AbsMAMlbh42fNtAyTFcY9rHG+RoquuMLKfncCnLjPDpDtq+asygoq61XdJ6VaWYRfCpOmqh4e5MdRpKVn1ooWaKvXx0qoB71NWXVGuAPsCt0F/X9+qUD5i3J+GQoBeKZWAdI1FniK5ess/GA+E08J58dRhRKBsmbW3x/yCURaEXc6QYY7F8mSRLxvjWzKs4VxVvxXsB/Z5yi1OPW+dqnpiRareJuxf8yuFVLN1j1HL+EZOmqcbZqah22TgRzMl4MoAGvgewrVXv8utm7xIL19kOU1AorMhYHuhkRfgO/ihllVCTtz0So+39BjU3mpGMRfy5qEPKD9b/9a6Y0GETlfDxD+As5lB7su1dDy5vgW+U6Hu8ix+AZABgzSUsmC2UzhwaohF4X3pQLnfQbxsPosO5LvDz0vCGx6dNXUBDALFQ7tKKeu60PXatRR8NFE2cYtXSv0rf4GFOCtg6a4qOLKicI2ZXy2NgwwCQbTRivQYCjoLWLo7UPv8U/1RBEZjbFsp3VR/7QVFT+tsIYibaLTcL3gJzzgXnY6N7FIeeffUwqqQVIfAD3hRrZ14ygMSPTwuMN+xRuBnvgTaErFte1HyP/a5hxzWTfepHKK9zd5s="
  before_install:
  - export PATH=$HOME:$PATH
  - export HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit
  - travis_retry curl -L https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
  - chmod +x ./hugo
  - mv ./hugo $HOME/bin/hugo
install:
  - rm -rf _site
  - yarn install
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - chmod +x $HOME/cf
  - mv $HOME/cf $HOME/bin/cf
  - cp ./_scripts/autopilot-linux $HOME/
  - chmod a+x $HOME/autopilot-linux
  - ./_scripts/before_deploy.sh
script:
  - ./node_modules/.bin/gulp build
cache:
  yarn: true
  #directories:
  #  - node_modules
branches:
  only:
    - master
    - development
deploy:
  - provider: script
    script:
      - ./_scripts/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - development
#after_deploy:
 # - ./_scripts/algolia.sh
