sudo: false
dist: trusty
git:
  depth: 20000 # We're cloning a max of xxx commits, so the author date is correct
language: node_js
env:
  global:
    - GET_ENV_VAR=./_scripts/get_env.sh
    - GOPATH="${HOME}/.go_workspace"
    - HUGO_ENV=$($GET_ENV_VAR)
    - CF_APP=docs
    - CF_API=https://api.run.pivotal.io
    - CF_USERNAME=robert.rumyantsev@mendix.com
    - CF_ORGANIZATION=mxrobert-org
    - CF_SPACE=docs
    - CF_CLI_VERSION=6.22.2
    - HUGO_VERSION=0.31.1
    - secure: "biykGM6RknKxsoudBeDVTK2IM/IYR3RT1fFg1tPdOfET1NarHzUI37MObokIKz5jqvQ64O4M7+yfc6ONcD5SVvcdomWFrAiSSuy8zavXwYfX9poQ+Sf8mBihYUJ+Y78jjc0cKXRsF/mbktl0hx1YFMAotuVucQbNh3bXPPWgeSonMxdoSFg/mAAqx1tXmmLzXw4GFygE5veawNdXwEyz+9aoGuj9ByNAXZbAOOQHMDnBtyBp7s/gor58ojDPqo/isMuUDp7q5UKH6giYaJZ4Fe5hXx5WqEH/CMwp1mQRwHL9AJkFAoyUEL169X2hNlhJUpePjTkDIGauHeThF2YpZ/ciGw2+i+C16WgxU32SLjd1WptQ9sM+P3GH+p/msufBVfsy6VieV1/li7mPFtbb57ykywzLWnuGXSw5IT3CMWmSb5Oa/5DmieZr+SGhZwM4sf744fwxZ7ZEHZoPNGZ42BkwkuNWZel7+N/uyfHmF+ReZhJ2v7iMLoVyPDpaghwywUDjcwjiy251KvHxuWH3h2WcGLWpP5mxwRqae6cWDppV7yIZ3FUZeL0YzFaiuYCgpdIofuk4G+lwK2ZjWkuP8mAMkO1YZsNXSKh3wTwq/ydaGM+5+8xHHSBq66acKfQYAZcRoc4kv6o9LgYGNZayz1eEOGPuWWGf6KaqD3baCig=" 
before_install:
  - export PATH=$HOME:$PATH
  - export HUGO_PACKAGE=hugo_${HUGO_VERSION}_Linux-64bit
  - travis_retry curl -L https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/$HUGO_PACKAGE.tar.gz | tar xz
  - chmod +x ./hugo
  - mv ./hugo $HOME/bin/hugo
install:
  - rm -rf _site
  - yarn install
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=$CF_CLI_VERSION"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - chmod +x $HOME/cf
  - mv $HOME/cf $HOME/bin/cf
  - cp ./_scripts/autopilot-linux $HOME/
  - chmod a+x $HOME/autopilot-linux
  - ./_scripts/before_deploy.sh
script:
  - ./node_modules/.bin/gulp build
cache:
  yarn: true
  #directories:
  #  - node_modules
branches:
  only:
    - master
    - development
deploy:
  - provider: script
    script:
      - ./_scripts/deploy.sh
    skip_cleanup: true
    on:
      branch:
        - master
        - development
#after_deploy:
 # - ./_scripts/algolia.sh
